#!/bin/bash

BUILD_REQS=('/mnt/abuilds /mnt/repository /mnt/install-lists')
source $SCRIPTS_DIR/fs_tools

chroot_add_resolv_conf() {
  local chrootdir=$1 resolv_conf=$1/etc/resolv.conf

  # Handle resolv.conf as a symlink to somewhere else.
  if [[ -L "$chrootdir/etc/resolv.conf" ]]; then
    # readlink(1) should always give us *something* since we know at this point
    # it's a symlink. For simplicity, ignore the case of nested symlinks.
    resolv_conf=$(readlink "$chrootdir/etc/resolv.conf")
    if [[ $resolv_conf = /* ]]; then
      resolv_conf=$chrootdir$resolv_conf
    else
      resolv_conf=$chrootdir/etc/$resolv_conf
    fi

    # ensure file exists to bind mount over
    if [[ ! -f $resolv_conf ]]; then
      install -Dm644 /dev/null "$resolv_conf" || return 1
    fi
  fi

  fs_add_mount /etc/resolv.conf "$resolv_conf" --bind
}

chroot_basic_mount() {
  local DIR=$1
  fs_add_mount proc "$DIR/proc" -t proc -o nosuid,noexec,nodev
  fs_add_mount sys "$DIR/sys" -t sysfs -o nosuid,noexec,nodev,ro
  fs_add_mount udev "$DIR/dev" -t devtmpfs -o mode=0755,nosuid
  fs_add_mount devpts "$DIR/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec
  fs_add_mount shm "$DIR/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev
  fs_add_mount run "$DIR/run" -t tmpfs -o nosuid,nodev,mode=0755
  fs_add_mount tmp "$DIR/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
}

chroot_build_mount() {
  local DIR=$1
  for req in $BUILD_REQS; do
    mkdir -p "${DIR}${req}"
    fs_add_mount $req "${DIR}${req}" -o bind
  done
}

chroot_mount() {
  local DIR=$1
  chroot_basic_mount $DIR
  chroot_build_mount $DIR
  chroot_add_resolv_conf $DIR
}

chroot_do() {
  local DIR=$1
  shift
  chroot $DIR /bin/bash -c "$@"
}
